const data = {
  products: [
    {
      //_id: '1',
      name: 'Ladies Casual Wear',
      code: 'LCW001',
      slug: 'Ladies-Casual-Wear',
      category: 'Ladies Casual Wear',
      colour: 'white',
      size: 'L',
      image: '/images/Ladies_Casual_Wear.png', // 679px × 829px
      price: 120000,
      countInStock: 10,
      brand: 'Gobinthan Garments',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality and stylish Stage Background',
    },
    {
      //_id: '2',
      name: 'Ladies Home Wear',
      code: 'LHW001',
      slug: 'Ladies-Home-Wear',
      category: 'Ladies Home Wear',
      colour: 'white',
      size: 'XL',
      image: '/images/Ladies_Home_Wear.png', // 679px × 829px
      price: 120000,
      countInStock: 10,
      brand: 'Gobinthan Garments',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality and stylish Stage Background',
    },
    {
      //_id: '3',
      name: 'Ladies Fashion Wear',
      code: 'LFW001',
      slug: 'Ladies-Fashion-Wear',
      category: 'Ladies Fashion Wear',
      colour: 'white',
      size: 'M',
      image: '/images/Ladies_Fashion_Wear.png', // 679px × 829px
      price: 120000,
      countInStock: 10,
      brand: 'Gobinthan Garments',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality and stylish Stage Background',
    },
    {
      //_id: '4',
      name: 'Customizable T-Shirts',
      code: 'CTS001',
      slug: 'Customizable-T-Shirts',
      category: 'Customizable T-Shirts',
      colour: 'white',
      size: 'L',
      image: '/images/Customizable_tshirts.png', // 679px × 829px
      price: 120000,
      countInStock: 10,
      brand: 'Gobinthan Garments',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality and stylish Stage Background',
    },
    {
      //_id: '5',
      name: 'School Uniforms',
      code: 'SU001',
      slug: 'School-Uniforms',
      category: 'School Uniforms',
      colour: 'white',
      size: 'XL',
      image: '/images/School_Uniforms.png', // 679px × 829px
      price: 120000,
      countInStock: 10,
      brand: 'Gobinthan Garments',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality and stylish Stage Background',
    },
    {
      //_id: '6',
      name: 'Bed Clothes',
      code: 'BC001',
      slug: 'Bed-Clothes',
      category: 'Bed Clothes',
      colour: 'white',
      size: 'S',
      image: '/images/Bed_Clothes.png', // 679px × 829px
      price: 120000,
      countInStock: 10,
      brand: 'Gobinthan Garments',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality and stylish Stage Background',
    },
  ],
};
export default data;
